sync_latest_webhooks:
  every: 3s
  class: ConsumeWebHooksJob
  queue: main
  description: "This will take all recently added webhooks and sync them"

sync_github_updaters:
  every: 5m
  class: GithubUpdaterJob
  queue: gh_update
  description: "This will update github description in function of Pivotal Tracker tickets"

sync_milestone:
  every: 5m
  class: MilestoneUpdaterJob
  queue: gh_update
  description: "This will check all the issues and update them if they have a unsynchronised milestone"